### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by dafei1288** [fla-sil/PyTorrent#11]
Could you please remove the file 'PyTorrent/Package_Metadata/pypi_packages/sqlalchemy-gbase8t' for my personal reason . I'm the owner of sqlalchemy-gbase8t , you can send a email to check .

**Comment by fla-sil** [comment]
https://github.com/fla-sil/PyTorrent/commit/aaaa2cdf5c8f4c2f5bf5c6c2dc6bdc2f2a148260
